<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AcVendor\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'AcVendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'AcVendor\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'AcVendor\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'AcVendor\\PhpDocReader\\' => array($vendorDir . '/php-di/phpdoc-reader/src/PhpDocReader'),
    'AcVendor\\Laravel\\SerializableClosure\\' => array($vendorDir . '/laravel/serializable-closure/src'),
    'AcVendor\\Invoker\\' => array($vendorDir . '/php-di/invoker/src'),
    'AcVendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'AcVendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'AcVendor\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'AcVendor\\DI\\' => array($vendorDir . '/php-di/php-di/src'),
    'AcVendor\\Brick\\Money\\' => array($vendorDir . '/brick/money/src'),
    'AcVendor\\Brick\\Math\\' => array($vendorDir . '/brick/math/src'),
);
