name: Deploy (SFTP) - Staging
# noop change to ensure workflow registration

on:
  push:
    branches: [ modal-staging ]
    paths:
      - 'wp-content/themes/hello-elementor-child-tpb/**'
      - 'wp-content/mu-plugins/tpb-quickview/**'
      - '.github/workflows/deploy-staging.yml'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit SHA, tag, or branch to deploy'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: SFTP deploy child theme (staging)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:   ${{ secrets.SFTP_HOST_STAGING }}
          port:     ${{ secrets.SFTP_PORT_STAGING }}
          username: ${{ secrets.SFTP_USER_STAGING }}
          password: ${{ secrets.SFTP_PASS_STAGING }}
          sftp_only: true
          local_path:  'wp-content/themes/hello-elementor-child-tpb/*'
          remote_path: '/html/wp-content/themes/hello-elementor-child-tpb'
          delete_remote_files: false

      - name: SFTP deploy mu-plugins/tpb-quickview (staging)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:   ${{ secrets.SFTP_HOST_STAGING }}
          port:     ${{ secrets.SFTP_PORT_STAGING }}
          username: ${{ secrets.SFTP_USER_STAGING }}
          password: ${{ secrets.SFTP_PASS_STAGING }}
          sftp_only: true
          local_path:  'wp-content/mu-plugins/tpb-quickview/*'
          remote_path: '/html/wp-content/mu-plugins/tpb-quickview'
          delete_remote_files: false

      - name: Flush caches (staging)
        run: |
          curl -fsS "${{ secrets.SITE_URL_STAGING }}/?tpb_deploy_flush=${{ secrets.DEPLOY_TOKEN_STAGING }}" || true


